registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/vm1.crt
    REGISTRY_HTTP_TLS_KEY: /certs/vm1.key
  volumes:
    - /vagrant/ssl:/certs
